[package]
name = "afrocreate-contracts"
version = "0.1.0"
edition = "2021"
description = "Arbitrum Stylus smart contracts for AfroCreate Collective - Web3 platform for African creators"
license = "MIT"
authors = ["AfroCreate Team"]

[dependencies]
stylus-sdk = "0.5.0"
alloy-primitives = "0.7.0"
alloy-sol-types = "0.7.0"
mini-alloc = "0.4.2"
hex = "0.4"

[dev-dependencies]
tokio = { version = "1.35.0", features = ["full"] }
ethers = "2.0.0"
eyre = "0.6.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
export-abi = ["stylus-sdk/export-abi"]
default = []

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "check"
path = "src/bin/check.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"
codegen-units = 1
overflow-checks = false

[profile.test]
opt-level = 1
debug = true